"""Initial migration - create Todo table

Revision ID: 3b99dc296013
Revises: 
Create Date: 2026-01-15 15:53:16.175210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b99dc296013'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Todo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Title', sa.String(length=200), nullable=False),
    sa.Column('Description', sa.Text(), nullable=True),
    sa.Column('_is_deleted', sa.Boolean(), nullable=False, server_default=sa.text('false')),
    sa.Column('CreatedOn', sa.Date(), nullable=False, server_default=sa.text('CURRENT_DATE')),
    sa.Column('DueDate', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Todo')
    # ### end Alembic commands ###
