"""Initial migration - create Todo table

Revision ID: 3b99dc296013
Revises: 
Create Date: 2026-01-15 15:53:16.175210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b99dc296013'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Todo', schema=None) as batch_op:
        batch_op.alter_column('Title',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               nullable=False)
        batch_op.alter_column('_is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('CreatedOn',
               existing_type=sa.DATE(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_DATE'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Todo', schema=None) as batch_op:
        batch_op.alter_column('CreatedOn',
               existing_type=sa.DATE(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_DATE'))
        batch_op.alter_column('_is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('Title',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###
